apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-deploy
spec:
  selector:
    matchLabels:
      app: minio
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: minio
    spec:
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: minio-pvc
      containers:
      - name: minio
        image: minio/minio:latest
        args:
        - server
        - /storage
        - --address
        - :9000
        - --console-address
        - :9090
        resources:
          limits:
            memory: "512Mi"
            cpu: "1"
        ports:
        - containerPort: 9000
          hostPort: 9000
        - containerPort: 9090
          hostPort: 9090
        volumeMounts:
          - name: storage
            mountPath: "/storage"
