apiVersion: v1
kind: Service
metadata:
  name: minio-service
spec:
  type: LoadBalancer
  selector:
    app: minio
  ports:
  - name: api
    port: 9000
    targetPort: 9000
    protocol: TCP
  - name: console
    port: 9090
    targetPort: 9090
