name: "Homework 2: Infrastructure Setup"

env:
  IMAGE_PREFIX: prjctr-prodml-h2

on:
  pull_request:
    branches:
      - main
    
jobs:
  test:
    name: Dummy Test
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        run: |
          echo 'Hello World!'

      - name: Checkout
        uses: actions/checkout@v3

      - name: List files
        run: |
          ls -R h2-infrastructure-setup/**

  publish-ml-image:
    name: Build and push ML Docker Image
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ml
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: h2-infrastructure-setup/ml/
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/${{ env.IMAGE_PREFIX }}-${{ env.IMAGE_NAME }}:latest

  publish-webapp-image:
    name: Build and push WebApp Docker Image
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: webapp
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: h2-infrastructure-setup/webapp/
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/${{ env.IMAGE_PREFIX }}-${{ env.IMAGE_NAME }}:latest
    
  test-k8s-deploy:
    name: Test K8s Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Create K8s Kind Cluster
        uses: helm/kind-action@v1.4.0
      
      - name: Checkout source
        uses: actions/checkout@v3
      
      - name: Deploy application
        run: |
          kubectl create -f h2-infrastructure-setup/webapp/deploy.yml
          kubectl wait --for=condition=available --timeout=90s deployment/deploy-webapp

  test-k8s-job:
    name: Test K8s Job
    runs-on: ubuntu-latest
    steps:
      - name: Create K8s Kind Cluster
        uses: helm/kind-action@v1.4.0
      
      - name: Checkout source
        uses: actions/checkout@v3
      
      - name: Run job
        run: |
          kubectl create -f h2-infrastructure-setup/ml/job.yml
          kubectl wait --for=condition=complete --timeout=90s job/job-ml
