name: "Homework 3: Storage and Processing"

on:
  pull_request:
    branches:
      - main
    
jobs:
  test-k8s-minio-deploy:
    name: Test Minio K8s Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Create K8s Kind Cluster
        uses: helm/kind-action@v1.4.0
      
      - name: Checkout source
        uses: actions/checkout@v3
      
      - name: Deploy Minio
        run: |
          cd h3-storage-and-processing
          kubectl create -f k8s/minio-pvc.yml
          kubectl create -f k8s/minio-deploy.yml
          kubectl create -f k8s/minio-service.yml
          kubectl wait --for=condition=available --timeout=90s deployment/minio-deploy

  publish-test-image:
    name: Build and push Test Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: h3-storage-and-processing/
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/prjctr-prodml-h3-test:latest
  
  test-minio-client:
    name: Test Minio Python Client
    needs: [test-k8s-minio-deploy, publish-test-image]
    runs-on: ubuntu-latest
    steps:
      - name: Create K8s Kind Cluster
        uses: helm/kind-action@v1.4.0
      
      - name: Checkout source
        uses: actions/checkout@v3
      
      - name: Deploy Minio
        run: |
          cd h3-storage-and-processing
          kubectl create -f k8s/minio-pvc.yml
          kubectl create -f k8s/minio-deploy.yml
          kubectl create -f k8s/minio-service.yml
          kubectl wait --for=condition=available --timeout=90s deployment/minio-deploy

      - name: Run test job
        run: |
          cd h3-storage-and-processing
          kubectl create -f k8s/test-job.yml
          kubectl wait --for=condition=complete job/minio-client-test
          kubectl logs job/minio-client-test
