name: Homework 2 CI

env:
  IMAGE_PREFIX: prjctr-prodml-h2

on:
  push:
    paths:
      - "h2-infrastucture-setup/**"
  pull_request:
    branches:
      - main
    
jobs:
  test:
    name: Dummy Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Hello World
        run: |
          echo 'Hello World!'

      - name: List files
        run: |
          ls -R h2-infrastucture-setup/**

  publish-ml-image:
    name: Build and push ML Docker Image
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ml
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: h2-infrastucture-setup/ml/
          push: true
          tags: ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_PREFIX }}-${{ env.IMAGE_NAME }}:latest
    